'''@authors  Simone Orsi (305461) and Martina Gualtieri (308783)'''

ARENA_WIDTH, ARENA_HEIGHT = 490, 262
BACKGROUND, HOLE, ROCK, CANNON, UFO, ROVER, BULLET = "BACKGROUND", "HOLE", "ROCK", "CANNON", "UFO", "ROVER", "BULLET"
BACKGROUND_IMAGE, FOREGROUND_IMAGE = "moon-patrol-bg.png", "moon-patrol-fg.png"
GAME_OVER_IMAGE, SCORE_LEVEL_IMAGE = "game-over.png", "score-level.png"
BACKGROUND_MUSIC, GAME_OVER_MUSIC = "background.mp3", "game-over.mp3"
FIRST_DELIMITER_RULES, SECOND_DELIMITER_RULES = "###", "---"
FIRST_DELIMITER_COMMAND, SECOND_DELIMITER_COMMAND = "[", "]"

BULLET_UP, BULLET_RIGHT, BULLET_LEFT, BULLET_DOWN = "up", "right", "left", "down"
ROVER_DESTRUCTION_ANIMATION_0, ROVER_DESTRUCTION_ANIMATION_1, ROVER_DESTRUCTION_ANIMATION_2 = 14, 22, 30
NEGATIVE_X = -50
OBSTACLE_SPEED = -4
PLAYER_1, PLAYER_2 = "player-1", "player-2"
MOUNTAINS, HILLS, CITY, GROUND = "mountains", "hills", "city", "ground"
SHOOTER_UFO, BONUS_UFO = "shooter", "bonus"
SMALL_SIZE, BIG_SIZE = "small", "big"
JUMPING_SPRITE, DEFAULT_SPRITE = "jumping-sprite", "default-sprite"
MAX_IMAGE_WIDTH, GROUND_LEVEL, MIN_DISTANCE = 512, 255, 100
MARGIN, TOP_MARGIN_BONUS_UFO, TOP_MARGIN_SHOOTER_UFO = 20, 70, 50
MAX_TIMER = 120
HIGH_PRIORITY, MEDIUM_HIGH_PRIORITY, MEDIUM_LOW_PRIORITY, LOW_PRIORITY = 1, 2, 3, 4
STEP_LEVEL, LEVEL_NUMBERS = 300, 4
MAX_BULLETS = 2
BULLET_SPEED, BULLET_LEFT_SPEED = 4, 8

BLACK, WHITE = (0, 0, 0), (255, 255, 255)
SMALL_FONT_SIZE, MEDIUM_FONT_SIZE, BIG_FONT_SIZE = 9, 12, 15
SINGLE_PLAYER, MULTIPLAYER, START_GAME, ROVER_1, ROVER_2, GAME_OVER = "SINGLE PLAYER", "MULTIPLAYER", "START GAME", "ROVER 1", "ROVER 2", "GAME OVER"
KEY_INVINCIBLE_ROVER_1, KEY_INVINCIBLE_ROVER_2 = "r", "p"

